USE DB_COURSE
GO

ALTER DATABASE DB_COURSE SET ALLOW_SNAPSHOT_ISOLATION ON

WAITFOR DELAY '00:00:05'
BEGIN TRAN
UPDATE Map SET map_name='de_vertigo' WHERE map_id=10
WAITFOR DELAY '00:00:05'
COMMIT TRAN

--ALTER DATABASE DB_COURSE SET ALLOW_SNAPSHOT_ISOLATION OFF
--UPDATE Map SET map_name='de_vertigo' WHERE map_id=10
--SELECT * FROM Map